### ISSUE TITLE
[Feature Request]: Packet ID in HTTP POST Url

### ISSUE THREAD

**Issue by edhor1608** [jakoblorz/autofone#2]
--to localhost/api

-> Package (ID:1) 
--> localhost/api/1

**Comment by jakoblorz** [comment]
Fixed with https://github.com/jakoblorz/metrikxd/commit/f4709f4d6c4f6ac092f8f512c99aa577abd2ba97, introduced `{{packetID}}` placeholder for the --to argument @edhor1608 
First subsequent successful release build with https://github.com/jakoblorz/metrikxd/commit/faa1b2ad80ab878b93067c90bbd8f0faeb7f6fd9
